#!/bin/sh

regex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

url=$(grep -Ei "$regex" | uniq | dmenu -l 10 -p "Copy:" -w "$WINDOWID")

echo "$url" | tr -d '\n' | xsel -i -b 
